// @ts-nocheck -- Upstream is compiled without strict mode; host adapters are checked separately.
// Derived from dolphindb/vscode-extension/src/languageserver (Apache-2.0).
// Generated by scripts/sync_language.py. Do not edit; see provenance.json.
import { CompletionItemKind, InsertTextFormat, Position, MarkupKind, DiagnosticSeverity, SymbolKind } from 'vscode-languageserver-types';
import type { CompletionItem, TextEdit, Range, Hover, DocumentSymbol, Diagnostic, MarkupContent } from 'vscode-languageserver-types';
import type { TextDocument } from 'vscode-languageserver-textdocument';
import { SymbolType } from './types';
import type { IParamMetadata, ISymbol, IFunctionMetadata, IVariableMetadata } from './types';
import { buildFunctionCommentDocs, createRegexForFunctionNames, extractFirstloadTableArgument, getLineContentsBeforePosition, isParenthesisBalanced, extractModuleName } from './utils';
import type { LanguageHost, TextDocumentPositionParams } from '../../language/contracts';
type CompletionParams = TextDocumentPositionParams;
type DefinitionParams = TextDocumentPositionParams;
import { createSqlCompletions } from './sql-completions';
export type DdbCompletionItem = CompletionItem & { order?: number };
export function createCompletions(host: LanguageHost) {
const {documents, symbolService, dbService, ddbModules} = host;
const getSqlCompletions = createSqlCompletions(host);
function getLineContent (document: TextDocument, line: number): string {
    const lineStart = Position.create(line, 0)
    const lineEnd = Position.create(line + 1, 0)
    
    const range = {
        start: lineStart,
        end: lineEnd,
    }
    
    const text = document.getText(range)
    
    // 如果行不存在，返回 ''
    if (!text)
        return ''
        
        
    // 去掉行尾的换行符
    return text.trimEnd()
}

class CompletionsService {
    
    symbolService = symbolService
    dbService = dbService
    getSelectCompletions: typeof getSqlCompletions = getSqlCompletions.bind(this)
    
    getFunctionSnippets (position: TextDocumentPositionParams): DdbCompletionItem[] {
        const symbols = symbolService.getSymbols(position.textDocument.uri)
        const functionSymbols: ISymbol<typeof SymbolType.Function>[] = symbols.filter(s => s.type === SymbolType.Function) as ISymbol<typeof SymbolType.Function>[]
        const functionCompletions: CompletionItem[] = functionSymbols.map(s => ({
                label: s.name,
                kind: CompletionItemKind.Function,
                documentation: s.metadata?.comments ? buildFunctionCommentDocs(s.metadata.comments) : '',
                insertText:
                    `${s.name}(\${0})`,
                insertTextFormat: InsertTextFormat.Snippet
            }))
        return [...functionCompletions]
    }
    
    getVariableSnippets (position: TextDocumentPositionParams): DdbCompletionItem[] {
        const completionItems: CompletionItem[] = [ ]
        const uri = position.textDocument.uri
        const currentPos = position.position
        
        // 获取所有符号
        const symbols: ISymbol[] = symbolService.getSymbols(uri)
        
        
        // 找出所有作用域包含当前位置的符号
        const symbolsInScope = symbols.filter(symbol => {
            if (!symbol.metadata || !('scope' in symbol.metadata))
                return false
            return isPositionInScope(currentPos, symbol.metadata.scope as [Position, Position])
        })
        
        if (symbolsInScope.length === 0)
            return completionItems
            
        const notDuplicateSymbols: ISymbol[] = [ ]
        const duplicateSymbols: ISymbol[] = [ ]
        for (const symbol of symbolsInScope)
            // 不要滤掉不重复的符号
            if (!hasDuplicatesByKey(symbolsInScope, 'name'))
                notDuplicateSymbols.push(symbol)
            else
                duplicateSymbols.push(symbol)
                
                
        // 按作用域起始位置降序排序，起始位置越靠近当前位置的作用域越靠前
        duplicateSymbols.sort((a, b) => {
            const aStart = a.metadata!.scope[0]
            const bStart = b.metadata!.scope[0]
            if (aStart.line !== bStart.line)
                return bStart.line - aStart.line
                
            return bStart.character - aStart.character
        })
        
        // 获取最靠近的作用域起始位置
        let closestSymbols: ISymbol[] = [ ]
        if (duplicateSymbols.length > 0) {
            const closestScopeStart = duplicateSymbols[0].metadata!.scope[0]
            closestSymbols = duplicateSymbols.filter(symbol => {
                const scopeStart = symbol.metadata!.scope[0]
                return scopeStart.line === closestScopeStart.line && scopeStart.character === closestScopeStart.character
            })
        }
        
        const symbolsToComplete = [...notDuplicateSymbols, ...closestSymbols]
        
        // 生成补全项
        symbolsToComplete.forEach(symbol => {
            if (symbol.type === SymbolType.Variable && symbol.metadata) {
                const varMeta = symbol.metadata as IVariableMetadata
                completionItems.push({
                    label: symbol.name,
                    kind: CompletionItemKind.Variable,
                    documentation: varMeta.comments || '',
                })
            } else if (symbol.type === SymbolType.Param && symbol.metadata)
                completionItems.push({
                    label: symbol.name,
                    kind: CompletionItemKind.Variable,
                    detail: `Parameter of ${(symbol.metadata as IParamMetadata).funcname}`,
                })
                
        })
        
        return completionItems
    }
    
    getModuleUseSnippets (position: TextDocumentPositionParams): DdbCompletionItem[] {
        const items: CompletionItem[] = [ ]
        const allModules = ddbModules.getModules().filter(module => module.moduleName)
        for (const module of allModules) {
            const moduleName = module.moduleName
            const textDocument = documents.get(position.textDocument.uri)
            const line = textDocument.getText({
                start: { line: position.position.line, character: 0 },
                end: { line: position.position.line + 1, character: 0 }
            })
            
            // 如果当前行是 use catalog，则不提供模块补全
            if (/^use\s+catalog/i.test(line.trim())) 
                continue
            
            const insertText = line.trim().startsWith('use') ? `${moduleName}` : `use ${moduleName}`
            items.push({
                label: `use ${moduleName}`,
                kind: CompletionItemKind.Module,
                documentation: `Use module ${moduleName}`,
                insertText: insertText,
            })
        }
        
        return items
    }
    
    getModuleTopLevelFunctions (position: TextDocumentPositionParams): DdbCompletionItem[] {
        const documentUri = position.textDocument.uri
        const uses: string[] = symbolService.symbols.get(documentUri)?.use ?? [ ]
        const currentPisitionModuleName = symbolService.symbols.get(documentUri)?.module
        const items: CompletionItem[] = [ ]
        const allModules = ddbModules.getModules()
            .filter(module => module.moduleName)
            // 不要导入当前文件的模块
            .filter(module => module.moduleName !== currentPisitionModuleName)
        for (const mod of allModules) {
            const modulePath = mod.filePath
            const symbolsInPath = symbolService.getSymbols(modulePath).filter(s => s.type === SymbolType.Function) as ISymbol<typeof SymbolType.Function>[]
            for (const s of symbolsInPath) {
                const top_level = s.metadata.top_level
                if (top_level) {
                    const argumentCompletions = s.metadata.argnames.map((arg, i) => `\$\{${i + 1}:${arg}\}`)
                    const additionalTextEdits = [ ]
                    if (!uses.includes(mod.moduleName))
                        if (currentPisitionModuleName)
                            // 如果存在 moduleName，则在第二行添加 `use ${moduleName}`
                            additionalTextEdits.push({
                                range: {
                                    start: { line: 1, character: 0 }, // 第二行（行索引从0开始）
                                    end: { line: 1, character: 0 }
                                },
                                newText: `use ${mod.moduleName}\n`
                            })
                        else
                            // 如果不存在 moduleName，则在第一行插入 `use ${moduleName}`
                            additionalTextEdits.push({
                                range: {
                                    start: { line: 0, character: 0 },
                                    end: { line: 0, character: 0 }
                                },
                                newText: `use ${mod.moduleName}\n`
                            })
                    items.push(
                        {
                            label: s.name,
                            kind: CompletionItemKind.Function,
                            documentation: {
                                kind: MarkupKind.Markdown,
                                value: `Function from module \`${mod.moduleName}\`\n` +
                                    (s.metadata?.comments ? buildFunctionCommentDocs(s.metadata.comments).value : '')
                            },
                            insertText: `${mod.moduleName}::${s.name}(${argumentCompletions.join(', ')})`,
                            insertTextFormat: InsertTextFormat.Snippet,
                            additionalTextEdits
                        }
                    )
                }
                
            }
        }
        return items
    }
    
    buildDatabaseCompletionItem (url: string, skipQuota: boolean, commonOrder: boolean) {
        return {
            label: skipQuota ? `${url}` : `"${url}"`,
            kind: CompletionItemKind.Value,
            insertText: skipQuota ? `${url}` : `"${url}"`,
            insertTextFormat: InsertTextFormat.Snippet,
            order: commonOrder ? undefined : 1
        }
    }
    
    buildColNameCompletionItem (colName: string, skipQuota: boolean, commonOrder: boolean) {
        return {
            label: skipQuota ? `${colName}` : `"${colName}"`,
            kind: CompletionItemKind.Value,
            insertText: skipQuota ? `${colName}` : `"${colName}"`,
            insertTextFormat: InsertTextFormat.Snippet,
            order: commonOrder ? undefined : 2
        }
    }
    
    buildCatalogCompletionItem (url: string, skipQuota: boolean, commonOrder: boolean) {
        return {
            label: skipQuota ? `${url}` : `"${url}"`,
            kind: CompletionItemKind.Value,
            insertText: skipQuota ? `${url}` : `"${url}"`,
            insertTextFormat: InsertTextFormat.Snippet,
            order: commonOrder ? undefined : 1
        }
    }
    
    buildTableCompletionItem (tableName: string, skipQuota: boolean, commonOrder: boolean) {
        return {
            label: skipQuota ? `${tableName}` : `"${tableName}"`,
            kind: CompletionItemKind.Value,
            insertText: skipQuota ? `${tableName}` : `"${tableName}"`,
            insertTextFormat: InsertTextFormat.Snippet,
            order: commonOrder ? undefined : 2
        }
    }
    
    buildSharedTableCompletionItem (tableName: string, skipQuota: boolean, commonOrder: boolean) {
        return {
            label: skipQuota ? `${tableName}` : `"${tableName}"`,
            kind: CompletionItemKind.Value,
            insertText: skipQuota ? `${tableName}` : `"${tableName}"`,
            insertTextFormat: InsertTextFormat.Snippet,
            order: commonOrder ? undefined : 1
        }
    }
    
    getDatabsaseSnippets (position: TextDocumentPositionParams): DdbCompletionItem[] {
        const lineBefore = getLineContentsBeforePosition(documents.get(position.textDocument.uri).getText(), position.position)
        const dburls = dbService.dfsDatabases
        const items: CompletionItem[] = [ ]
        const isBalanced = isParenthesisBalanced(lineBefore)
        const funcs = ['loadTable', 'database', 'dropDatabase']
        if (createRegexForFunctionNames(funcs).exec(lineBefore)) {
            const skipQuota = /["'\`]/.test(lineBefore[lineBefore.length - 1])
            items.push(...dburls.map(url => this.buildDatabaseCompletionItem(url, skipQuota, isBalanced)))
        }
        return items
    }
    
    getCatalogSnippets (position: TextDocumentPositionParams): DdbCompletionItem[] {
        const items: CompletionItem[] = [ ]
        const catalogs = dbService.catalogs
        const lineBefore = getLineContentsBeforePosition(documents.get(position.textDocument.uri).getText(), position.position)
        const isBalanced = isParenthesisBalanced(lineBefore)
        const funcs = ['dropCatalog']
        if (createRegexForFunctionNames(funcs).exec(lineBefore)) {
            const skipQuota = /["'\`]/.test(lineBefore[lineBefore.length - 1])
            items.push(...catalogs.map(url => this.buildCatalogCompletionItem(url, skipQuota, isBalanced)))
        }
        return items
    }
    
    async getTableSnippets (position: TextDocumentPositionParams): Promise<DdbCompletionItem[]> {
        const items: CompletionItem[] = [ ]
        const lineBefore = getLineContentsBeforePosition(documents.get(position.textDocument.uri).getText(), position.position)
        const dburl = extractFirstloadTableArgument(lineBefore)
        const isBalanced = isParenthesisBalanced(lineBefore)
        if (dburl)
            if (dburl.startsWith("'") || dburl.startsWith('"')) {
                let db = dburl.replaceAll("'", '').replaceAll('"', '')
                await dbService.update_table_of_db(db)
                const tables = dbService.dbTables.get(db)
                const skipQuota = /["'\`]/.test(lineBefore[lineBefore.length - 1])
                if (tables)
                    items.push(...tables.map(tableName => (this.buildTableCompletionItem(tableName, skipQuota, isBalanced))))
            }
        return items
    }
    
    filterHighestOrderCompletions (items: DdbCompletionItem[]): DdbCompletionItem[] {
        if (!items.some(item => item.order !== undefined))
            return items
            
        const highestOrder = items.reduce(
            (max, item) => (item.order !== undefined && item.order > max ? item.order : max),
            -Infinity
        )
        
        return items.filter(item => item.order === highestOrder)
    }
    
    getCommonSnippets (position: TextDocumentPositionParams): DdbCompletionItem[] {
        return [
            {
                label: 'def',
                kind: CompletionItemKind.Snippet,
                documentation: 'Define a function',
                insertText: [
                    'def ${1:functionName}(${2:params}) {',
                    '\t${3:// body}',
                    '}'
                ].join('\n'),
                insertTextFormat: InsertTextFormat.Snippet
            }
        ]
    }
    
    async complete (position: TextDocumentPositionParams, isBlankTrigger = false): Promise<CompletionItem[]> {
        const selectCompletions = await this.getSelectCompletions(position)
        const tableCompletions = await this.getTableSnippets(position)
        const commonCompletions = [
            ...this.getDatabsaseSnippets(position),
            ...this.getCatalogSnippets(position),
            ...this.getCommonSnippets(position),
            ...this.getFunctionSnippets(position),
            ...this.getVariableSnippets(position),
            ...this.getModuleUseSnippets(position),
            ...this.getModuleTopLevelFunctions(position),
        ]
        const items: DdbCompletionItem[] = [
            ...selectCompletions,
            ...tableCompletions,
            ...(isBlankTrigger ? [ ] : commonCompletions),
        ]
        return this.filterHighestOrderCompletions(items)
    }
}

// 辅助函数：判断当前位置是否在作用域内
function isPositionInScope (pos: Position, scope: [Position, Position]) {
    const [start, end] = scope
    if (pos.line < start.line || pos.line > end.line)
        return false
    if (pos.line === start.line && pos.character < start.character)
        return false
    if (pos.line === end.line && pos.character > end.character)
        return false
    return true
}

function hasDuplicatesByKey (arr, key) {
    const seen = new Map() // 或使用普通对象 {}  但 Map 效率更高
    
    for (const item of arr) {
        if (seen.has(item[key]))
            return true
            
        seen.set(item[key], item)
    }
    return false
}

return new CompletionsService();
}
