// @ts-nocheck -- Upstream is compiled without strict mode; host adapters are checked separately.
// Derived from dolphindb/vscode-extension/src/languageserver (Apache-2.0).
// Generated by scripts/sync_language.py. Do not edit; see provenance.json.
import { CompletionItemKind, InsertTextFormat, Position, MarkupKind, DiagnosticSeverity, SymbolKind } from 'vscode-languageserver-types';
import type { CompletionItem, TextEdit, Range, Hover, DocumentSymbol, Diagnostic, MarkupContent } from 'vscode-languageserver-types';
import type { TextDocument } from 'vscode-languageserver-textdocument';
import { SymbolType } from './types';
import type { IParamMetadata, ISymbol, IFunctionMetadata, IVariableMetadata } from './types';
import { buildFunctionCommentDocs, createRegexForFunctionNames, extractFirstloadTableArgument, getLineContentsBeforePosition, isParenthesisBalanced, extractModuleName } from './utils';
import type { LanguageHost, TextDocumentPositionParams } from '../../language/contracts';
type CompletionParams = TextDocumentPositionParams;
type DefinitionParams = TextDocumentPositionParams;
export function createDiagnostics({ddbModules}: LanguageHost) {
async function validateTextDocument (textDocument: TextDocument): Promise<Diagnostic[]> {
    const text = textDocument.getText()
    const lines = text.split('\n')
    
    const diagnostics: Diagnostic[] = [ ]
    
    lines.forEach((line, index) => {
        diagnostics.push(...validateUseModule(line, index))
    })
    
    return diagnostics
}

function validateUseModule (line: string, lnindex: number): Diagnostic[] {
    // 索引必须已经建立
    if (!ddbModules.getIsInitModuleIndex())
        return [ ]
    const ln = line.trim()
    if (ln.startsWith('use')) {
        const moduleName = extractModuleName(ln)
        const modules = ddbModules.getModules()
        const module = modules.find(e => e.moduleName === moduleName)
        if (moduleName && !module) 
            return [{
                severity: DiagnosticSeverity.Warning,
                range: {
                    start: Position.create(lnindex, 0),
                    end: Position.create(lnindex, line.length)
                },
                message: `Cannot find module ${moduleName} in current workspace`,
                source: 'dolphindb'
            }]
        
    }
    return [ ]
}

return validateTextDocument;
}
