// Derived from dolphindb/vscode-extension, src/connector.ts (Apache-2.0).
// Generated by scripts/sync_upstream.py. Host UI is implemented in ../panel.tsx.
import { DDB, urgent, type DdbObj, type DdbOptions } from 'dolphindb/browser.js';
import { strcmp } from 'xshell/utils.browser.js';
import { NodeType, type DdbNode, type TNodeType } from './commons';

export class DdbConnection {
    ddb: DDB;
    connected = false;
    logined = false;
    client_auth = false;
    version = '';
    node_type!: TNodeType;
    node_alias = '';
    controller_alias = '';
    nodes: DdbNode[] = [];
    node?: DdbNode;
    controller?: DdbNode;
    datanode?: DdbNode;

    constructor(public url: string, public name: string, options: DdbOptions) {
        this.ddb = new DDB(url, options);
    }

    async connect () {
        if (this.ddb.connected && /* 有可能 websocket 连接成功但 login 失败 */ this.connected)  // 这个方法后面有些操作会有副作用，已连接的话直接跳过吧
            return false
        
        await this.ddb.connect()
        
        await Promise.all([
            this.update_logined(),
            this.get_node_type(),
            this.get_node_alias(),
            this.get_controller_alias(),
            this.get_version(),
            this.check_client_auth()
        ])
        
        await this.get_cluster_perf()
        
        this.connected = true
        
        return true
    }

    disconnect () {
        this.ddb.disconnect()
        this.logined = false
    }

    async update_logined () {
        if (this.ddb.connected)
            // 此处约定当前连接用户名为 guest 即为未登录状态
            this.logined = (await this.ddb.call<DdbObj<DdbObj<string>[]>>('getCurrentSessionAndUser')).value[1].value !== 'guest'
        else
            this.logined = false
    }

    async get_node_type () {
        const { value: node_type } = await this.ddb.call<DdbObj<TNodeType>>('getNodeType', undefined, urgent)
        this.node_type = node_type
        return node_type
    }

    async get_node_alias () {
        const { value: node_alias } = await this.ddb.call<DdbObj<string>>('getNodeAlias', undefined, urgent)
        this.node_alias = node_alias
        return node_alias
    }

    async get_controller_alias () {
        const { value: controller_alias } = await this.ddb.call<DdbObj<string>>('getControllerAlias', undefined, urgent)
        this.controller_alias = controller_alias
        return controller_alias
    }

    async get_cluster_perf () {
        const nodes = (
            await this.ddb.invoke<DdbNode[]>('getClusterPerf', [true], {
                urgent: true,
                
                ... this.client_auth || (this.node_type === NodeType.controller || this.node_type === NodeType.single)
                    ? { }
                    : { node: this.controller_alias },
            })
        ).sort((a, b) => strcmp(a.name, b.name))
        
        let node: DdbNode | undefined, controller: DdbNode | undefined, datanode: DdbNode | undefined
        
        for (const _node of nodes) {
            if (_node.name === this.node_alias)
                node = _node
            
            if (_node.mode === NodeType.controller)
                if (_node.isLeader)
                    controller = _node
                else
                    controller ??= _node
            
            if (_node.mode === NodeType.data)
                datanode ??= _node
        }
        
        this.nodes = nodes
        this.node = node
        this.controller = controller
        this.datanode = datanode
    }

    async get_version () {
        this.version = (await this.ddb.invoke<string>('version'))
            .split(' ')[0]
    }

    async check_client_auth () {
        try {
            const client_auth = await this.ddb.invoke<boolean>('isClientAuth', undefined, urgent)
            return this.client_auth = client_auth
        } catch {
            return false
        }
    }
}
