// Extracted from dolphindb/vscode-extension/src/commands.ts and connector.ts (Apache-2.0).
// Generated by scripts/sync_upstream.py; only terminal output is adapted to Jupyter.
import type { DDB } from 'dolphindb/browser.js';

export async function executeCode(ddb: DDB, text: string, iline: number, onPrint: (text: string) => void) {
        return await ddb.eval(
            `line://${iline + 1}\n` +
            `${text.replace(/\r\n/g, '\n')}`,
            {
                listener (message) {
                    if (!ddb.connected)
                        return
                    
                    const { type, data } = message
                    if (type === 'print')
                        onPrint(data)
                }
            }
        )
}

export const funcdefs = {
    load_table_variable_schema: {
        dolphindb: 
            'def load_table_variable_schema (table_name) {\n' +
            '    return schema(objByName(table_name))\n' +
            '}\n',
            
        python: 
            'def load_table_variable_schema (table_name):\n' +
            '    return schema(objByName(table_name))\n',
        
        q: 'load_table_variable_schema: {[table_name] schema get table_name}\n'
    },
    peek_table: {
        dolphindb:
            'def peek_table (db_path, tb_name) {\n' +
            '    return select top 100 * from loadTable(db_path, tb_name)\n' +
            '}\n',
            
        python:
            'def peek_table (db_path, tb_name):\n' +
            '    return select top 100 * from loadTable(db_path, tb_name)\n',
            
        q: 'peek_table: {[db_path; tb_name] select[100] from loadTable[db_path; tb_name]}'
    },
    load_table_schema: {
        dolphindb: 
            'def load_table_schema (db_path, tb_name) {\n' +
            '    return schema(loadTable(db_path, tb_name))\n' +
            '}\n',
            
        python:
            'def load_table_schema (db_path, tb_name):\n' +
            '    return schema(loadTable(db_path, tb_name))\n',
            
        q: 'load_table_schema: {[db_path; tb_name] schema loadTable[db_path; tb_name]}'
    },
    load_database_schema: {
        dolphindb: 
            'def load_database_schema (db_path) {\n' +
            '    return schema(database(db_path))\n' +
            '}\n',
            
        python:
            'def load_database_schema (db_path):\n' +
            '    return schema(database(db_path))\n',
        
        q: 'load_database_schema: {[db_path] schema database db_path}'
    },
};
