"""Vendor the upstream language algorithms with explicit, request-local Jupyter hosts."""

import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UPSTREAM = ROOT / "upstream/vscode-extension/src/languageserver"
DEST = ROOT / "frontend/upstream/language"
HEADER = (
    "// @ts-nocheck -- Upstream is compiled without strict mode; host adapters are checked separately.\n"
    "// Derived from dolphindb/vscode-extension/src/languageserver (Apache-2.0).\n"
    "// Generated by scripts/sync_language.py. Do not edit; see provenance.json.\n"
)


def generate():
    sources = {name: (UPSTREAM / f"{name}.ts").read_text(encoding="utf-8")
               for name in ["types", "utils", "symbols", "completions", "sql-completions", "definitions", "diagnostics"]}
    outputs = {}
    for name in ("types", "utils", "symbols"):
        code = sources[name].replace("vscode-languageserver/node", "vscode-languageserver-types")
        code = code.replace("./utils.ts", "./utils").replace("./types.ts", "./types")
        if name == "utils":
            code = code[code.index("export function getWordAtPosition"):]
            code = "import { MarkupKind, type MarkupContent, type Position } from 'vscode-languageserver-types';\n" + code
        if name == "symbols":
            code = code.replace("escapeRegExp, readFileByPath", "escapeRegExp")
            code = code.replace("import { connection } from './connection.ts'", "")
            code = code.replace("export class SymbolService {", "export class SymbolService {\n    constructor(private readFile: (path: string) => Promise<string>) {}")
            code = code.replace("await readFileByPath(module.filePath)", "await this.readFile(module.filePath)")
            code = code.replace("export const symbolService = new SymbolService()", "")
            code = code.replace("connection.onDocumentSymbol(params => {\n    const filePath = params.textDocument.uri", "export function documentSymbols(symbolService: SymbolService, filePath: string) {")
            code = code.rstrip().removesuffix("})") + "}\n"
        outputs[f"{name}.ts"] = HEADER + code

    imports = (
        "import { CompletionItemKind, InsertTextFormat, Position, MarkupKind, DiagnosticSeverity, SymbolKind } from 'vscode-languageserver-types';\n"
        "import type { CompletionItem, TextEdit, Range, Hover, DocumentSymbol, Diagnostic, MarkupContent } from 'vscode-languageserver-types';\n"
        "import type { TextDocument } from 'vscode-languageserver-textdocument';\n"
        "import { SymbolType } from './types';\n"
        "import type { IParamMetadata, ISymbol, IFunctionMetadata, IVariableMetadata } from './types';\n"
        "import { buildFunctionCommentDocs, createRegexForFunctionNames, extractFirstloadTableArgument, getLineContentsBeforePosition, isParenthesisBalanced, extractModuleName } from './utils';\n"
        "import type { LanguageHost, TextDocumentPositionParams } from '../../language/contracts';\n"
        "type CompletionParams = TextDocumentPositionParams;\n"
        "type DefinitionParams = TextDocumentPositionParams;\n"
    )
    sql = sources["sql-completions"][sources["sql-completions"].index("export async function getSqlCompletions"):]
    sql = sql.replace("export async function", "async function")
    outputs["sql-completions.ts"] = HEADER + imports + (
        "export function createSqlCompletions({documents, dbService}: LanguageHost) {\n" + sql + "\nreturn getSqlCompletions;\n}\n"
    )
    completions = sources["completions"][sources["completions"].index("function getLineContent"):]
    completions = completions.replace("export class", "class").replace("export function", "function")
    completions = completions[:completions.index("export const completionsService")]
    # Resolve shadowing per name. The upstream duplicate check puts every symbol
    # into one group if any name is repeated, dropping unrelated completions.
    first = completions.index("        const notDuplicateSymbols")
    last = completions.index("        // 生成补全项", first)
    completions = completions[:first] + """        const nearestByName = new Map<string, ISymbol>()
        for (const symbol of symbolsInScope) {
            const previous = nearestByName.get(symbol.name)
            const start = symbol.metadata!.scope[0]
            const previousStart = previous?.metadata!.scope[0]
            if (!previousStart || start.line > previousStart.line ||
                start.line === previousStart.line && start.character >= previousStart.character)
                nearestByName.set(symbol.name, symbol)
        }
        const symbolsToComplete = [...nearestByName.values()]

""" + completions[last:]
    completions = re.sub(r"\nfunction hasDuplicatesByKey \(arr, key\) \{.*?\n\}\n", "\n", completions, count=1, flags=re.S)
    outputs["completions.ts"] = HEADER + imports + (
        "import { createSqlCompletions } from './sql-completions';\n"
        "export type DdbCompletionItem = CompletionItem & { order?: number };\n"
        "export function createCompletions(host: LanguageHost) {\n"
        "const {documents, symbolService, dbService, ddbModules} = host;\n"
        "const getSqlCompletions = createSqlCompletions(host);\n" + completions +
        "return new CompletionsService();\n}\n"
    )
    definitions = sources["definitions"][sources["definitions"].index("function getWordAtPosition"):]
    definitions = definitions.replace("connection.onDefinition(async ({ textDocument, position }: DefinitionParams) => {", "async function definition({ textDocument, position }: DefinitionParams) {")
    definitions = definitions.replace("connection.onHover(async params => {", "async function hover(params: TextDocumentPositionParams) {")
    definitions = re.sub(r"^\}\)$", "}", definitions, flags=re.M)
    outputs["definitions.ts"] = HEADER + imports + (
        "export function createDefinitions({documents, symbolService, ddbModules}: LanguageHost) {\n"
        "const isPositionInScope = (pos, [start,end]) => (pos.line > start.line || pos.line === start.line && pos.character >= start.character) && (pos.line < end.line || pos.line === end.line && pos.character <= end.character);\n"
        + definitions + "\nreturn {definition, hover};\n}\n"
    )
    diagnostics = sources["diagnostics"][sources["diagnostics"].index("async function validateTextDocument"):]
    outputs["diagnostics.ts"] = HEADER + imports + (
        "export function createDiagnostics({ddbModules}: LanguageHost) {\n" + diagnostics + "\nreturn validateTextDocument;\n}\n"
    )
    outputs["provenance.json"] = json.dumps({
        "repository": "https://github.com/dolphindb/vscode-extension",
        "revision": subprocess.check_output(["git", "-C", str(UPSTREAM), "rev-parse", "HEAD"], text=True).strip(),
        "sources": {f"src/languageserver/{name}.ts": hashlib.sha256(code.encode()).hexdigest() for name, code in sources.items()},
        "adaptations": ["Browser-safe LSP data types replace Node transport", "Replace global services with request-local injected hosts", "Route module reads through Jupyter Contents", "Expose callbacks as callable methods; keep completion, symbol, SQL and documentation algorithms", "Resolve variable completion shadowing per name so reassignment retains unrelated symbols"],
    }, indent=2) + "\n"
    return outputs


if __name__ == "__main__":
    import sys
    DEST.mkdir(parents=True, exist_ok=True)
    for name, text in generate().items():
        target = DEST / name
        if "--check" in sys.argv:
            if target.read_text(encoding="utf-8") != text:
                raise SystemExit(f"Upstream language extraction differs: {name}")
        else:
            target.write_text(text, encoding="utf-8", newline="\n")
    print("Upstream language extraction verified." if "--check" in sys.argv else "Extracted upstream language services.")
