"""Extract portable connection methods verbatim, with documented host/type adaptations."""

import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UPSTREAM = ROOT / "upstream/vscode-extension"
DEST = ROOT / "frontend/upstream"
METHODS = [
    "connect",
    "disconnect",
    "update_logined",
    "get_node_type",
    "get_node_alias",
    "get_controller_alias",
    "get_cluster_perf",
    "get_version",
    "check_client_auth",
]


def generate():
    source = (UPSTREAM / "src/connector.ts").read_text(encoding="utf-8")
    connection = source[source.index("export class DdbConnection") :]
    methods = []
    for name in METHODS:
        match = re.search(rf"^    (?:async )?{name} \([^\n]*\) \{{.*?^    \}}", connection, re.M | re.S)
        if not match:
            raise RuntimeError(f"Upstream method changed: {name}")
        method = match[0]
        # VS Code presentation is supplied by the Jupyter sidebar.
        method = re.sub(r"^[ \t]*console\.log.*\n", "", method, flags=re.M)
        method = re.sub(r"^        this\.(description|contextValue) = .*\n", "", method, flags=re.M)
        # Replace a prototype helper and make implicit upstream types explicit for strict TS.
        method = method.replace(".slice_to(' ')", ".split(' ')[0]")
        method = method.replace(
            "this.ddb.call('getCurrentSessionAndUser')",
            "this.ddb.call<DdbObj<DdbObj<string>[]>>('getCurrentSessionAndUser')",
        )
        method = method.replace(
            "let node: DdbNode, controller: DdbNode, datanode: DdbNode",
            "let node: DdbNode | undefined, controller: DdbNode | undefined, datanode: DdbNode | undefined",
        )
        methods.append(method)
    header = """// Derived from dolphindb/vscode-extension, src/connector.ts (Apache-2.0).
// Generated by scripts/sync_upstream.py. Host UI is implemented in ../panel.tsx.
import { DDB, urgent, type DdbObj, type DdbOptions } from 'dolphindb/browser.js';
import { strcmp } from 'xshell/utils.browser.js';
import { NodeType, type DdbNode, type TNodeType } from './commons';

export class DdbConnection {
    ddb: DDB;
    connected = false;
    logined = false;
    client_auth = false;
    version = '';
    node_type!: TNodeType;
    node_alias = '';
    controller_alias = '';
    nodes: DdbNode[] = [];
    node?: DdbNode;
    controller?: DdbNode;
    datanode?: DdbNode;

    constructor(public url: string, public name: string, options: DdbOptions) {
        this.ddb = new DDB(url, options);
    }

"""
    revision = subprocess.check_output(["git", "-C", str(UPSTREAM), "rev-parse", "HEAD"], text=True).strip()
    commons = (UPSTREAM / "src/commons.ts").read_text(encoding="utf-8")
    return {
        "connection.ts": header + "\n\n".join(methods) + "\n}\n",
        "commons.ts": "// Copied unchanged from dolphindb/vscode-extension/src/commons.ts (Apache-2.0).\n"
        + commons,
        "provenance.json": json.dumps(
            {
                "repository": "https://github.com/dolphindb/vscode-extension",
                "revision": revision,
                "connectorSha256": hashlib.sha256(source.encode()).hexdigest(),
                "methods": METHODS,
                "adaptations": [
                    "Use browser SDK entry points",
                    "Remove VS Code presentation/logging",
                    "Explicit strict TypeScript types",
                    "Use String.split instead of String.slice_to",
                ],
            },
            indent=2,
        )
        + "\n",
    }


if __name__ == "__main__":
    import sys

    outputs = generate()
    if "--check" in sys.argv:
        for filename, content in outputs.items():
            if (DEST / filename).read_text(encoding="utf-8") != content:
                raise SystemExit(f"Upstream extraction differs: {filename}")
        print("Upstream connection extraction verified.")
    else:
        DEST.mkdir(parents=True, exist_ok=True)
        for filename, content in outputs.items():
            (DEST / filename).write_text(content, encoding="utf-8", newline="\n")
        print(f"Extracted {len(METHODS)} upstream connection methods.")
